---
# defaults file for build_airgap
rke2_version: "{{ global_rke2_version }}"
helm_version: "{{ global_helm_version }}"
CERT_VERSION: "{{ global_CERT_VERSION }}"
RANCHER_VERSION: "{{ global_RANCHER_VERSION }}"
LONGHORN_VERSION: "{{ global_LONGHORN_VERSION }}"
NEU_VERSION: "{{ global_NEU_VERSION }}"
directory_package: "{{ global_directory_package_build }}"
tar_zst_name: "{{ global_package_name }}"
path_to_package_zst: "{{ global_path_to_package_zst }}"
list_directory_package:
    - "{{ directory_package }}/rke2_{{ rke2_version }}"
    - "{{ directory_package }}/helm"
    - "{{ directory_package }}/utils"
    - "{{ directory_package }}/images/cert"
    - "{{ directory_package }}/images/rancher"
    - "{{ directory_package }}/images/longhorn"
    - "{{ directory_package }}/images/registry"
    - "{{ directory_package }}/images/neuvector"

# extras RPM
rke2_common_repo_version: "{{ global_rke2_common_repo_version }}"
rke2_common_rpm_version: "{{ global_rke2_common_rpm_version }}"
rke2_selinux_repo_version: "{{ global_rke2_selinux_repo_version }}"
rke2_selinux_rpm_version: "{{ global_rke2_selinux_rpm_version }}"