---
# tasks file for mount_nfs
- name: Gather facts
  ansible.builtin.setup:
    gather_subset:
      - "distribution"
      - "distribution_major_version"
      - "!min"
  when: >
    ansible_os_family is not defined

- name: Tasks for RHEL-like OS
  ansible.builtin.import_tasks: rhel.yml
  when:
    - ansible_os_family == "RedHat"