# mount NFS directory
- block:
  - name: Install NFS packages
    dnf:
      name: "{{ item }}"
      state: present
    with_items:
      - nfs-utils

  - name: Create mount directory
    ansible.builtin.file:
      path: "{{ nfs_mount_path }}"
      state: directory
      recurse: yes

  - name: Add NFS entry to /etc/fstab
    ansible.builtin.lineinfile:
      path: /etc/fstab
      line: "{{ master_ip }}:{{ export_nfs_path }} {{ nfs_mount_path }} nfs rw,hard,rsize=1048576,wsize=1048576 0 0"

  - name: Mount NFS share
    ansible.posix.mount:
      path: "{{ nfs_mount_path }}"
      src: "{{ master_ip }}:{{ export_nfs_path }}"
      fstype: nfs
      opts: rw,hard,rsize=1048576,wsize=1048576
      state: mounted

  become: true
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version | int >= 8