---
# defaults file for install_controler
rke2_version: "{{ global_rke2_version }}"
airgap_path: "{{ global_directory_package_target }}/rancher"
airgap_rke2_path: "{{ airgap_path }}/rke2_{{ rke2_version }}"
airgap_rke2_common_rpm_path: "{{ airgap_rke2_path }}/{{ global_rke2_common_rpm_version }}.el{{ ansible_distribution_major_version }}.x86_64.rpm"
airgap_rke2_selinux_rpm_path: "{{ airgap_rke2_path }}/{{ global_rke2_selinux_rpm_version }}.el{{ ansible_distribution_major_version }}.noarch.rpm"
