---
# defaults file for install_controler
rke2_version: "{{ global_rke2_version }}"
admin_user: "{{ global_install_user }}"
airgap_path: "{{ global_directory_package_target }}/rancher"
airgap_rke2_path: "{{ airgap_path }}/rke2_{{ rke2_version }}"
airgap_utils_path: "{{ airgap_path }}/utils"
airgap_rke2_common_rpm_path: "{{ airgap_rke2_path }}/{{ global_rke2_common_rpm_version }}.el{{ ansible_distribution_major_version }}.x86_64.rpm"
airgap_rke2_selinux_rpm_path: "{{ airgap_rke2_path }}/{{ global_rke2_selinux_rpm_version }}.el{{ ansible_distribution_major_version }}.noarch.rpm"

# Firewall rules
controller_firewalld_rules: 
  inbound:
  - name: rke2
    zone: public
    ports:
    - {port: 443, protocol: tcp}
    - {port: 6443, protocol: tcp}
    - {port: 2379, protocol: tcp}
    - {port: 9345, protocol: tcp}
    - {port: 10250, protocol: tcp}
    - {port: 8472, protocol: udp}
    erase: true
