---
# defaults file for install_controler
admin_user: "{{ global_install_user }}"
master: "{{ global_master_ip }}"
control_plane_endpoint: "{{ global_rke2_api_ip }}"
rpm_install: "{{ global_rpm_install | bool }}"
tarball_install: "{{ global_tarball_install | bool }}"

# Fileserver
hauler_server: "{{ global_hauler_ip }}"
mount_path: "{{ global_directory_package_target }}"
mount_rke2_path: "{{ mount_path }}/fileserver"

# RKE2 config
rke2_kubeconfig_file: "/etc/rancher/rke2/rke2.yaml"

# Controller options
rke2_data_dir: "{{ global_rke2_data_dir }}"
rke2_cluster_cidr: "{{ global_rke2_cluster_cidr }}"
rke2_service_cidr: "{{ global_rke2_service_cidr }}"
rke2_cni: "{{ global_rke2_cni }}"
rke2_profile_activated: "{{ global_rke2_profile_activated }}"

# Firewall rules
controller_firewalld_rules:
  inbound:
    - name: rke2
      zone: public
      ports:
        - {port: 443, protocol: tcp}
        - {port: 6443, protocol: tcp}
        - {port: 2379, protocol: tcp}
        - {port: 9345, protocol: tcp}
        - {port: 10250, protocol: tcp}
        - {port: 8472, protocol: udp}
