---
# defaults file for install_controler
rke2_version: "{{ global_rke2_version }}"
admin_user: "{{ global_install_user }}"
master: "{{ global_master_ip }}"
control_plane_endpoint: "{{ master }}"

# Mount share
mount_path: "{{ global_directory_mount }}"
mount_rke2_path: "{{ mount_path }}/rke2_{{ rke2_version }}"
mount_utils_path: "{{ mount_path }}/utils"
mount_rke2_common_rpm_path: "{{ mount_rke2_path }}/{{ global_rke2_common_rpm_version }}.el{{ ansible_distribution_major_version }}.x86_64.rpm"
mount_rke2_selinux_rpm_path: "{{ mount_rke2_path }}/{{ global_rke2_selinux_rpm_version }}.el{{ ansible_distribution_major_version }}.noarch.rpm"

# RKE2 config
rke2_kubeconfig_file: "/etc/rancher/rke2/rke2.yaml"

# Controller options
rke2_data_dir: "{{ global_rke2_data_dir }}"
rke2_cluster_cidr: "{{ global_rke2_cluster_cidr }}"
rke2_service_cidr: "{{ global_rke2_service_cidr }}"
rke2_cni: "{{ global_rke2_cni }}"
rke2_profile_activated: "{{ global_rke2_profile_activated }}"
rke2_api_ip: "{{ global_rke2_api_ip }}"

# Firewall rules
controller_firewalld_rules:
  inbound:
    - name: rke2
      zone: public
      ports:
        - {port: 443, protocol: tcp}
        - {port: 6443, protocol: tcp}
        - {port: 2379, protocol: tcp}
        - {port: 9345, protocol: tcp}
        - {port: 10250, protocol: tcp}
        - {port: 8472, protocol: udp}
