---
# defaults file for install_common

# Mount share
mount_path: "{{ global_directory_package_target }}"

# RKE2
admin_user: "{{ global_install_user }}"
rke2_data_dir: "{{ global_rke2_data_dir }}"
hauler_server: "{{ global_hauler_ip }}"
