---
name: ansible
description: execute an ansible playbook

runs:
  using: composite
  steps:
    - name: Checkout files
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.7.3"

    - name: Get key
      run: |
        echo "$SSH_KEY" > .key
        chmod 400 .key
      shell: bash
      env:
        SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}

    - name: Terraform Init
      id: init
      run: |
        terraform init

    - name: Terraform plan
      id: plan
      run: |
        terraform plan -out=terraform.tfplan \
        -var "GITHUB_RUN_ID=$GITHUB_RUN_ID" \
        -var "do_token=${DO_PAT}" \
        -var "terraform_backend_bucket_name=github-action-${{ github.run_id }}"

    - name: Terraform Apply
      run: |
        terraform apply terraform.tfplan

    - name: Terraform plan delete stack
      id: plan
      run: |
        terraform plan -destroy -out=terraform.tfplan \
        -var "GITHUB_RUN_ID=$GITHUB_RUN_ID" \
        -var "do_token=${DO_PAT}" \
        -var "terraform_backend_bucket_name=github-action-${{ github.run_id }}"
      continue-on-error: true

    - name: Terraform Apply
      run: |
        terraform apply terraform.tfplan
      continue-on-error: true
