# Version products
global_rke2_version: "1.26.10"
global_helm_version: "3.11.3"
global_CERT_VERSION: "1.12.2"    
global_RANCHER_VERSION: "2.7.6" 
global_LONGHORN_VERSION: "1.5.1"
global_NEU_VERSION: "2.6.3"     

# extras RPM
global_rke2_common_rpm_version: "rke2-common-{{ rke2_version }}.rke2r1-0" #.el{{ ansible_distribution_major_version }}.x86_64.rpm
global_rke2_selinux_repo_version: "v0.16.stable.1"
global_rke2_selinux_rpm_version: "rke2-selinux-0.16-1"                    #.el{{ ansible_distribution_major_version }}.noarch.rpm

# General
global_install_user: "{{ install_user | default('kuberoot') }}"
global_directory_package_build: "{{ dir_build | default('$HOME/rkub') }}"

# Local
global_package_name: "{{ package_name | default('rke2_rancher_longhorn.zst') }}"
global_path_to_package_zst: "{{ global_directory_package_build }}/../{{ global_package_name }}"

# Target
global_directory_package_target: "{{ dir_target | default('/opt') }}"
global_directory_mount: "{{ dir_mount | default('/mnt/rkub') }}"

# Options RKE2
global_master_ip: "{{ master_ip | default(hostvars[groups['RKE2_CONTROLLERS'][0]]['ansible_default_ipv4']['address']) }}"
global_domain:    "{{ domain | default(hostvars[groups['RKE2_CONTROLLERS'][0]]['ansible_domain']) }}"

# Options - Not used yet
global_data_dir:  "/rke2"
global_cluster_cidr: "10.42.0.0/16" #Default Value
global_service_cidr: "10.43.0.0/16" #Default Value

# Longhorn 
default_longhorn_datapath: "{{ global_directory_package_target }}/longhorn"
global_longhorn_datapath: "{{ datapath | default(default_longhorn_datapath) }}"

# Rancher
global_rancher_password: "{{ password | default('BootStrapAllTheThings') }}"