global_rke2_version: "1.26.10"
global_helm_version: "3.11.3"
global_CERT_VERSION: "1.12.2"    
global_RANCHER_VERSION: "2.7.6" 
global_LONGHORN_VERSION: "1.5.1"
global_NEU_VERSION: "2.6.3"     
global_directory_package_build: "$HOME/rkub"
global_directory_package_target: "$HOME/rkub"
global_directory_registry: "/mnt/rkub/registry"
