---
# Version products
global_rke2_version: "1.27.10"
global_kubevip_version: "0.7.0"
global_helm_version: "3.14.0"
global_CERT_VERSION: "1.14.1"
global_RANCHER_VERSION: "2.8.1"
global_LONGHORN_VERSION: "1.6.0"
global_NEU_VERSION: "2.7.2"

# extras RPM
global_rke2_common_repo_version: "v{{ rke2_version }}%2Brke2r1"           #.stable.0
global_rke2_common_rpm_version: "rke2-common-{{ rke2_version }}.rke2r1-0" #.el{{ ansible_distribution_major_version }}.x86_64.rpm
global_rke2_selinux_repo_version: "v0.17.stable.1"
global_rke2_selinux_rpm_version: "rke2-selinux-0.17-1"                    #.el{{ ansible_distribution_major_version }}.noarch.rpm

# General
global_install_user: "{{ install_user | default('kuberoot') }}"
global_directory_package_build: "{{ dir_build | default('$HOME/rkub') }}"
global_archive_tar_zst_bool: "{{ archive | default('true') | bool }}"

# Local
global_package_name: "{{ package_name | default('rke2_rancher_longhorn.zst') }}"
global_path_to_package_zst: "{{ global_directory_package_build }}/../{{ global_package_name }}"

# Target
global_directory_package_target: "{{ dir_target | default('/opt') }}"
global_directory_mount: "{{ dir_mount | default('/mnt/rkub') }}"

# Options General
global_master_ip: "{{ master_ip | default(hostvars[groups['RKE2_CONTROLLERS'][0]]['ansible_default_ipv4']['address']) }}"
global_domain:    "{{ domain | default(hostvars[groups['RKE2_CONTROLLERS'][0]]['ansible_domain']) }}"

# Options RKE2 - Not used yet
global_rke2_data_dir: "{{ data_dir | default('/var/lib/rancher/rke2') }}"
global_rke2_ha_mode: true
global_rke2_api_ip: "{{ vip | default(global_master_ip) }}"
global_rke2_cluster_cidr: "10.42.0.0/16" #Default Value
global_rke2_service_cidr: "10.43.0.0/16" #Default Value
global_rke2_cni: "canal"
global_rke2_profile_activated: "{{ profile_cis | default('false') }}"
global_rke2_disable: "{{ disable | default(omit) }}" # Valid items to not deploy: rke2-canal, rke2-coredns, rke2-ingress-nginx, rke2-metrics-server

# Longhorn
default_longhorn_datapath: "{{ global_directory_package_target }}/longhorn"
global_longhorn_datapath: "{{ datapath | default(default_longhorn_datapath) }}"
global_longhorn_replica: 2

# Rancher
global_rancher_password: "{{ password | default('BootStrapAllTheThings') }}"
