---
# Version products
global_stable_channel: "{{ stable | default('false') }}"
global_all_wanted: "{{ all | default('false') }}"
global_extras_components:
  kubevip: "{{ kubevip | default(global_all_wanted) }}"
  rancher: "{{ rancher | default(global_all_wanted) }}"
  longhorn: "{{ longhorn | default(global_all_wanted) }}"
  neuvector: "{{ neuvector | default(global_all_wanted) }}"

global_versions:
  rke2: "1.31.8"
  kubevip: "0.9.1"
  cert_manager: "1.17.2"
  rancher: "2.11.1"
  longhorn: "1.8.1"
  neuvector: "5.3.4"
  helm: "3.16.4"
  nerdctl: "1.7.6"
  k9s: "0.32.4"
  hauler: "1.0.3"

global_rhel_version: "{{ el }}"

# General
global_install_user: "{{ install_user | default('kuberoot') }}"
global_method_install: "{{ method | default('tarball') }}"
global_rpm_install: "{{ global_method_install == 'rpm' }}"
global_tarball_install: "{{ global_method_install == 'tarball' }}"
global_airgap_install: "{{ airgap | default('true') }}"

# Local
global_directory_package_build: "{{ dir_build | default('$HOME/rkub') }}"
global_archive_tar_zst_bool: "{{ archive | default('true') | bool }}"
global_package_name: "{{ package_name | default('rkub.zst') }}"
global_path_to_package_zst: "{{ global_directory_package_build }}/../{{ global_package_name }}"

# Target
global_directory_package_target: "{{ dir_target | default('/opt/rkub') }}"

# Options General
global_hauler_ip: "{{ hauler_ip | default(hostvars[groups['RKE2_CONTROLLERS'][0]]['ansible_default_ipv4']['address']) }}"
global_master_ip: "{{ master_ip | default(hostvars[groups['RKE2_CONTROLLERS'][0]]['ansible_default_ipv4']['address']) }}"
global_domain:    "{{ domain | default(hostvars[groups['RKE2_CONTROLLERS'][0]]['ansible_default_ipv4']['address'] + '.sslip.io') }}"

# Options RKE2
global_rke2_data_dir: "{{ data_dir | default('/var/lib/rancher/rke2') }}"
global_rke2_ha_mode: false
global_rke2_api_ip: "{{ vip | default(global_master_ip) }}"
global_rke2_cluster_cidr: "10.42.0.0/16" #Default Value
global_rke2_service_cidr: "10.43.0.0/16" #Default Value
global_rke2_cni: "{{ cni | default('canal') }}"
global_rke2_profile_activated: "{{ profile_cis | default('false') }}"
global_rke2_disable: "{{ disable | default(omit) }}" # Valid items to not deploy: rke2-canal, rke2-coredns, rke2-ingress-nginx, rke2-metrics-server

# Etcd backup/restore
global_rke2_etcd_snapshot_backup_dir: "{{ backup_dir | default('etcd_snapshots') }}"
global_rke2_etcd_snapshot_file: "{{ backup_file | default('') }}"

# Etcd snapshot s3 options
# Set either all these values or `rke2_etcd_snapshot_file` and `rke2_etcd_snapshot_source_dir`

# rke2_etcd_snapshot_s3_options:
  # s3_endpoint: "" # required
  # access_key: "" # required
  # secret_key: "" # required
  # bucket: "" # required
  # snapshot_name: "" # required.
  # skip_ssl_verify: false # optional
  # endpoint_ca: "" # optional. Can skip if using defaults
  # region: "" # optional - defaults to us-east-1
  # folder: "" # optional - defaults to top level of bucket

# Longhorn
default_longhorn_datapath: "/data/longhorn"
global_longhorn_datapath: "{{ datapath | default(default_longhorn_datapath) }}"
global_longhorn_replica: 2

# Rancher
global_rancher_password: "{{ password | default('BootStrapAllTheThings') }}"
