---
# defaults file for deploy_rancher
rancher_servicename: "rancher"
rancher_domain: "{{ global_domain }}"
rancher_url: "{{ rancher_servicename }}.{{ rancher_domain }}"
rancher_password: "{{ global_rancher_password }}"

# General
admin_user: "{{ global_install_user }}"
master: "{{ global_master_ip }}"
airgap_install: "{{ global_airgap_install | bool }}"
