---
# Airgap
- name: "Deploy Neuvector"
  run_once: true
  become: true
  become_user: "{{ admin_user }}"
  become_method: ansible.builtin.sudo
  become_flags: "-i"
  when: airgap_install
  block:
    - name: Deploy helm charts
      kubernetes.core.helm:
        atomic: true
        name: "neuvector"
        chart_ref: "neuvector/core"
        release_namespace: "neuvector"
        create_namespace: true
        values:
          registry: "{{ master }}:5000"
          k3s:
            enabled: true
            runtimePath: /run/k3s/containerd/containerd.sock
          manager:
            image:
              repository: neuvector/manager
            ingress:
              enabled: true
              ingress:
                host: "{{ neuvector_url }}"
            svc:
              type: ClusterIP
          controller:
            image:
              repository: neuvector/controller
            pvc:
              enabled: true
              capacity: 500Mi
          enforcer:
            image:
              repository: neuvector/enforcer
          internal:
            certmanager:
              enabled: true
          cve:
            updater:
              image:
                repository: neuvector/updater
        kubeconfig: "/home/{{ admin_user }}/.kube/{{ inventory_hostname }}.yaml"

# Non-Airgap
- name: "Deploy Neuvector"
  run_once: true
  become: true
  become_user: "{{ admin_user }}"
  become_method: ansible.builtin.sudo
  become_flags: "-i"
  when: not airgap_install
  block:
    - name: Neuvector Versions needed
      ansible.builtin.import_role:
        name: set_versions
        tasks_from: only_neuvector
      run_once: true

    - name: Add Neuvector chart repo
      kubernetes.core.helm_repository:
        name: neuvector
        repo_url: "https://neuvector.github.io/neuvector-helm/"
        force_update: true

    - name: Deploy helm charts
      kubernetes.core.helm:
        atomic: true
        name: "neuvector"
        chart_ref: "neuvector/core"
        chart_version: "{{ neuvector_version }}"
        release_namespace: "neuvector"
        create_namespace: true
        values:
          k3s:
            enabled: true
            runtimePath: /run/k3s/containerd/containerd.sock
          manager:
            ingress:
              enabled: true
              ingress:
                host: "{{ neuvector_url }}"
            svc:
              type: ClusterIP
          controller:
            pvc:
              enabled: true
              capacity: 500Mi
        kubeconfig: "/home/{{ admin_user }}/.kube/{{ inventory_hostname }}.yaml"

# Common
- name: Display Neuvector URL
  ansible.builtin.debug:
    msg:  "Neuvector URL : {{ neuvector_url }}"
