---
# tasks file for deploy_neuvector
- name: Gather facts
  ansible.builtin.setup:
    gather_subset:
      - "default_ipv4"
      - "!all,!min"
  when: >
    ansible_default_ipv4 is not defined
  tags: [always]

- name: Deploy with the Helm Charts on master
  ansible.builtin.import_tasks: deploy.yml
  when: inventory_hostname in groups['RKE2_CONTROLLERS'][0]
