---
# handlers file for install_controler
- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Config file changed
  ansible.builtin.set_fact:
    rke2_restart_needed: true

- name: Service (re)started
  ansible.builtin.set_fact:
    rke2_restart_needed: false

- name: Restart rke2-server
  ansible.builtin.systemd:
    name: rke2-server.service
    state: restarted
  notify: "Service (re)started"