---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  #python: ee-requirements.txt
  galaxy: ee-requirements.yml
  #system: ee-bindeps.txt
  exclude:
      python:
        - docker
      system:
        - openshift-clients

# Custom Dependencies
additional_build_steps:
  prepend_base: |
    RUN whoami
    RUN cat /etc/os-release
  append_final: |
    RUN echo This is a post-install command!
    RUN ls -la $HOME
    RUN microdnf clean all
    RUN rm -rf /var/cache/dnf

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

options:
  package_manager_path: /usr/bin/microdnf

# Check documentation:
# https://docs.ansible.com/automation-controller/latest/html/userguide/ee_reference.html

# Run :
# ansible-builder build --tag test --container-runtime podman -f meta/execution-environment.yml
