---
version: 3

dependencies:
  python: meta/ee-requirements.txt
  galaxy: meta/ee-requirements.yml
  system: meta/ee-bindep.txt
  # custom
  arkade: meta/ee-arkade.txt
  images: meta/ee-images.txt

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

# Check documentation:
# https://docs.ansible.com/automation-controller/latest/html/userguide/ee_reference.html