---
version: 3

dependencies:
  python: meta/ee-requirements.txt
  galaxy: meta/ee-requirements.yml
  system: meta/ee-bindeps.txt

# Custom Dependencies
additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools
  append:
    - RUN $(MAKE) -C ./scripts/prerequis arkade
    - RUN $(MAKE) -C ./scripts/prerequis images

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

# Check documentation:
# https://docs.ansible.com/automation-controller/latest/html/userguide/ee_reference.html
