---
# Stable version from URL
- name: Set Rancher Versions variables
  when: stable_channel_wanted
  block:
    # export CERT_VERSION=$(curl -s https://api.github.com/repos/cert-manager/cert-manager/releases/latest | jq -r .tag_name)
    - name: Get Cert-Manager latest release
      ansible.builtin.uri:
        url: "https://api.github.com/repos/cert-manager/cert-manager/releases/latest"
        method: GET
        return_content: true
      register: cert_manager_release

    - name: Extract latest release tag
      ansible.builtin.set_fact:
        cert_manager_version: "{{ cert_manager_release.json.tag_name | regex_replace('^v', '') }}"

    # export RANCHER_VERSION=$(curl -s https://api.github.com/repos/rancher/rancher/releases/latest | jq -r .tag_name)
    - name: Get Rancher latest release
      ansible.builtin.uri:
        url: "https://api.github.com/repos/rancher/rancher/releases/latest"
        method: GET
        return_content: true
      register: rancher_release

    - name: Extract latest release tag
      ansible.builtin.set_fact:
        rancher_version: "{{ rancher_release.json.tag_name | regex_replace('^v', '') }}"

# Version defined in this Ansible collection
- name: Set Rancher Versions variables
  ansible.builtin.set_fact:
    cert_manager_version: "{{ global_versions['cert_manager'] }}"
    rancher_version: "{{ global_versions['rancher'] }}"
  when: not stable_channel_wanted

# Common
- name: Display Rancher version
  ansible.builtin.debug:
    msg:
      - "Cert-manager version to be installed is {{ cert_manager_version }}"
      - "Rancher version to be installed is {{ rancher_version }}"
