---
# Stable version from URL
- name: Set Kube-vip Versions variables
  when: stable_channel_wanted
  block:
    # export KUBEVIP_VERSION=$(curl -s https://api.github.com/repos/kube-vip/kube-vip/releases/latest | jq -r .tag_name)
    - name: Get Kube-vip latest release
      ansible.builtin.uri:
        url: "https://api.github.com/repos/kube-vip/kube-vip/releases/latest"
        method: GET
        return_content: true
      register: kubevip_release

    - name: Extract latest release tag
      ansible.builtin.set_fact:
        kubevip_version: "{{ kubevip_release.json.tag_name | regex_replace('^v', '') }}"

# Version defined in this Ansible collection
- name: Set Kube-vip Versions variables
  ansible.builtin.set_fact:
    kubevip_version: "{{ global_versions['kubevip'] }}"
  when: not stable_channel_wanted

# Common
- name: Display kube-vip version
  ansible.builtin.debug:
    msg:  "Kube-vip version to be installed is {{ kubevip_version }}"
