---
- name: RHEL version was not given in command line so need to be defined
  when: rhel_version == 'false'
  block:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - "distribution"
          - "distribution_major_version"
          - "!min"
      when: >
        ansible_os_family is not defined

    - name: Set rhel_version variable from non-RedHat systems
      ansible.builtin.set_fact:
        rhel_version: 8
      when: ansible_os_family != "RedHat"

    - name: Set rhel_version variable from a RedHat systems and take same version
      ansible.builtin.set_fact:
        rhel_version: "{{ ansible_distribution_major_version }}"
      when: ansible_os_family == "RedHat"

- name: Display RHEL version
  ansible.builtin.debug:
    msg: "Rkub Package is set now for RHEL version {{ rhel_version }}"
