---
# defaults file for uninstall_rke2
admin_user: "{{ global_install_user }}"
longhorn_datapath: "{{ global_longhorn_datapath }}"

firewalld_rules_to_remove:
  inbound:
    - name: rke2
      zone: public
      erase: true
