---
# defaults file for uninstall_rke2
admin_user: "{{ global_install_user }}"
export_nfs_path: "{{ global_directory_package_target }}/rancher"
nfs_mount_path: "{{ global_directory_mount }}"

firewalld_rules_to_remove: 
  inbound:
  - name: rke2
    zone: public
    erase: true