---
# tasks file for upload_package_zst
- name: Gather facts
  ansible.builtin.setup:
    gather_subset:
      - "distribution"
      - "distribution_major_version"
      - "!all,!min"
  when: >
    ansible_os_family is not defined
  tags: [always]

# Prompt
- name: Prompt for package zst path
  when: package_path is undefined
  block:
    - name: Conditionally prompt for package zst path
      ansible.builtin.pause:
        prompt: "Please give the absolute path to package zst"
        echo: true
      register: package_path_prompt

    - name: Set package_path
      ansible.builtin.set_fact:
        package_path: "{{ package_path_prompt['user_input'] }}"

# Prerequisites
- name: Install needed packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - zstd
    - rsync
  become: true
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version | int >= 8

- name: Ensure target directory exist and accessible to connexion user
  ansible.builtin.file:
    path: "{{ global_directory_package_target }}/rancher"
    state: directory
    recurse: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0770'
  become: true

# Rsync
- name: Synchronization of Monster zst package on first controler
  ansible.posix.synchronize:
    src: "{{ package_path }}"
    dest: "{{ global_directory_package_target }}"
    archive: false

- name: Unarchive Monster zst package on first controler
  ansible.builtin.unarchive:
    src: "{{ global_directory_package_target }}/{{ global_package_name }}"
    dest: "{{ global_directory_package_target }}/rancher"
    remote_src: true