- name: uninstall RKE2
  hosts: RKE2_CONTROLERS:RKE2_WORKERS
  gather_facts: false
  become: true
  vars_files: ../vars/main.yml
  tags: controler, worker
  roles:
  - {role: uninstall_rkub, tags: uninstall,}