---
# defaults file for install_worker
admin_user: "{{ global_install_user }}"
master: "{{ global_master_ip }}"
control_plane_endpoint: "{{ global_rke2_api_ip }}"
rpm_install: "{{ global_rpm_install | bool }}"
tarball_install: "{{ global_tarball_install | bool }}"
airgap_install: "{{ global_airgap_install | bool }}"

# Fileserver
hauler_server: "{{ global_hauler_ip }}"

# Worker options
rke2_data_dir: "{{ global_rke2_data_dir }}"
rke2_cluster_cidr: "{{ global_rke2_cluster_cidr }}"
rke2_service_cidr: "{{ global_rke2_service_cidr }}"
rke2_profile_activated: "{{ global_rke2_profile_activated }}"

# Firewall rules
worker_firewalld_rules:
  inbound:
    - name: rke2
      zone: public
      ports:
        - {port: 10250, protocol: tcp}
        - {port: 8472, protocol: udp}
