---
- name: Create the RKE2 manifests directory
  ansible.builtin.file:
    state: directory
    path: "{{ rke2_data_path }}/server/manifests"
    owner: root
    group: root
    mode: 0700

- name: Copy kube-vip files to first server
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ rke2_data_path }}/server/manifests/{{ item | basename | regex_replace('.j2$', '') }}"
    owner: root
    group: root
    mode: 0664
  with_fileglob:
    - "templates/airgap/kube-vip.yml.j2"
    - "templates/airgap/kube-vip-rbac.yml.j2"
