---
# Install regarding choosen method
- name: RKE2 Install tarball method
  vars:
    caller_role_name: worker
  ansible.builtin.import_role:
    name: install_rke2_common
    tasks_from: tarball_install
  when: tarball_install

- name: RKE2 Install rpm method
  vars:
    caller_role_name: worker
  ansible.builtin.import_role:
    name: install_rke2_common
    tasks_from: rpm_install
  when: rpm_install
