---
# tasks file for install_rke2_worker
- name: Gather facts
  ansible.builtin.setup:
    gather_subset:
      - "distribution"
      - "distribution_major_version"
      - "default_ipv4"
      - "selinux"
      - "!all,!min"
  when: >
    ansible_os_family is not defined
  tags: [always]

- name: Populate service facts
  ansible.builtin.service_facts: {}
  tags: [always]

- name: RKE2 firewalld
  vars:
    firewalld_rules: "{{ worker_firewalld_rules }}"
  ansible.builtin.import_role:
    name: set_firewalld
    tasks_from: main
  when:
    - ansible_facts['services']['firewalld.service'] is defined
    - ansible_facts['services']['firewalld.service']['state'] == "running"
  tags: firewalld

# Start install
- name: RKE2 common to worker and controler tasks
  vars:
    caller_role_name: worker
  ansible.builtin.import_role:
    name: install_rke2_common
    tasks_from: main
  tags: common

- name: RKE2 Install worker
  ansible.builtin.import_tasks: install.yml
  tags: install

- name: Tasks if SELinux is activated for RKE2 installation
  vars:
    caller_role_name: worker
  ansible.builtin.import_role:
    name: install_rke2_common
    tasks_from: selinux
  when: ansible_selinux['status'] == 'enabled'

# Utils
- name: RKE2 install nerdctl
  vars:
    caller_role_name: worker
  ansible.builtin.import_role:
    name: install_utils_nerdctl
    tasks_from: main
  tags: nerdctl
