---
# As root
- name: Start RKE2 worker
  become: true
  block:
    # Start
    - name: Mask RKE2 agent service on the first server
      ansible.builtin.systemd:
        name: "rke2-server.service"
        enabled: false
        masked: true

    - name: Start and enable rke2-server
      ansible.builtin.systemd:
        name: rke2-agent.service
        state: started
        enabled: true
      notify: "Service (re)started"
      register: rke2_service
      until: rke2_service is succeeded
      retries: 5
