- block: 

  - name: firewalld NFS port enabled 
    ansible.posix.firewalld:
      service: nfs
      permanent: true
      state: enabled 

  - name: Always reload firewalld
    ansible.builtin.service:
      name: firewalld
      state: reloaded

  become: true
  when:
    - ansible_facts['services']['firewalld.service'] is defined
    - ansible_facts['services']['firewalld.service']['state'] == "running"