---
# share out directory
- name: NFS share
  become: true
  block:
    - name: Install NFS packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - nfs-utils
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution_major_version | int >= 8

    - name: Share out directory via NFS
      ansible.builtin.lineinfile:
        path: /etc/exports
        line: "{{ export_nfs_path }} *(ro)"
      notify: Restart_NFS_Server

    - name: Enable and start NFS server service
      ansible.builtin.systemd:
        name: nfs-server
        enabled: true
        state: started

    - name: Create Symlink to get same path than other server
      ansible.builtin.file:
        src: "{{ export_nfs_path }}"
        dest: "{{ symlink_mount_path }}"
        state: link
      when: export_nfs_path != symlink_mount_path