---
# tasks file for export_nfs
- name: Gather facts
  ansible.builtin.setup:
    gather_subset:
      - "distribution"
      - "distribution_major_version"
      - "!min"
  when: >
    ansible_os_family is not defined

- name: Tasks for Linux
  ansible.builtin.import_tasks: selinux.yml

- name: Tasks for Linux
  ansible.builtin.import_tasks: firewalld.yml

- name: Tasks to install and setup NFS export
  ansible.builtin.import_tasks: install.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers