---
# Admin setup
- name: Admin setup
  become_user: "{{ admin_user }}"
  become: true
  block:
    - name: Remove old Kubeconfig file
      ansible.builtin.file:
        path: "$HOME/.kube/{{ inventory_hostname }}.yaml"
        state: absent

    - name: Ensure .kube dir exist
      ansible.builtin.file:
        path: "$HOME/.kube"
        state: directory
        mode: 0700
        recurse: true

    - name: Get Kubernetes config file
      run_once: true
      ansible.builtin.slurp:
        src: "{{ rke2_kubeconfig_file }}"
      register: kubeconfig_base64
      become: false

    - name: Copy kubeconfig in Admin home dir
      ansible.builtin.copy:
        content: "{{ kubeconfig_base64.content | b64decode | replace('127.0.0.1', control_plane_endpoint) }}"
        dest: "/home/{{ admin_user }}/.kube/{{ inventory_hostname }}.yaml"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        force: true
        remote_src: true
        mode: '0600'
      run_once: true
      become: false

    - name: Change localhost with master ip in kubeconfig
      ansible.builtin.lineinfile:
        path: "$HOME/.kube/{{ inventory_hostname }}.yaml"
        search_string: '127.0.0.1'
        line: "    server: https://{{ master }}:6443"

    - name: Update Admin .bashrc
      ansible.builtin.blockinfile:
        path: "$HOME/.bashrc"
        block: |
          export KUBECONFIG="~/.kube/{{ inventory_hostname }}.yaml"
          export CRI_CONFIG_FILE={{ rke2_data_dir }}/agent/etc/crictl.yaml
          PATH=$PATH:{{ rke2_data_dir }}/bin
        marker: "# {mark} ANSIBLE setup Kubeconfig and RKE2"

    # Install helm / k9s
    - name: Ensure .local/bin dir exist
      ansible.builtin.file:
        path: "$HOME/.local/bin/{{ item }}"
        state: directory
        mode: 0700
        recurse: true
      loop:
        - "helm"
        - "k9s"

    - name: Download helm bin to .local/bin
      ansible.builtin.unarchive:
        src: "http://{{ hauler_server }}:8080/helm.tar.gz"
        dest: "$HOME/.local/bin/helm"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: '0750'
        remote_src: true
        validate_certs: false

    - name: Download k9s bin to .local/bin
      ansible.builtin.unarchive:
        src: "http://{{ hauler_server }}:8080/k9s.tar.gz"
        dest: "$HOME/.local/bin/k9s"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: '0750'
        remote_src: true
        validate_certs: false
