---
# tasks file for install_controler
- name: Gather facts
  ansible.builtin.setup:
    gather_subset:
      - "distribution"
      - "distribution_major_version"
      - "default_ipv4"
      - "selinux"
      - "!all,!min"
  when: >
    ansible_os_family is not defined
  tags: [always]

- name: Populate service facts
  ansible.builtin.service_facts: {}
  tags: [always]

- name: RKE2 firewalld
  vars:
    firewalld_rules: "{{ controller_firewalld_rules }}"
  ansible.builtin.import_role:
    name: set_firewalld
    tasks_from: main
  when:
    - ansible_facts['services']['firewalld.service'] is defined
    - ansible_facts['services']['firewalld.service']['state'] == "running"
  tags: firewalld

# Start install
- name: RKE2 common tasks
  vars:
    caller_role_name: controller
  ansible.builtin.import_role:
    name: install_rke2_common
    tasks_from: main
  tags: common

# Install first node
- name: RKE2 config controler before install
  ansible.builtin.import_tasks: config.yml
  when: inventory_hostname in groups['RKE2_CONTROLLERS'][0]
  tags: config

- name: RKE2 Install controler
  ansible.builtin.import_tasks: install.yml
  when: inventory_hostname in groups['RKE2_CONTROLLERS'][0]
  tags: install

- name: RKE2 start controller
  ansible.builtin.import_tasks: start.yml
  when: inventory_hostname in groups['RKE2_CONTROLLERS'][0]
  tags: start

- name: RKE2 Get Token
  ansible.builtin.import_tasks: token.yml
  when: inventory_hostname in groups['RKE2_CONTROLLERS'][0]
  tags: token

- name: Admin user setup
  ansible.builtin.import_tasks: admin.yml
  when: inventory_hostname in groups['RKE2_CONTROLLERS'][0]
  tags: admin

- name: Setup Ansible controler with new cluster
  ansible.builtin.import_tasks: localhost.yml
  when: inventory_hostname in groups['RKE2_CONTROLLERS'][0]
  tags: localhost

# Install other controllers
# ...

# Utils
- name: RKE2 install nerdctl
  vars:
    caller_role_name: controller
  ansible.builtin.import_role:
    name: install_utils_nerdctl
    tasks_from: main
  tags: nerdctl
