---
# RPM
- name: Set repo Hauler Air Gap Server
  ansible.builtin.yum_repository:
    name: hauler
    description: "Hauler Air Gap Server"
    baseurl: "http://{{ hauler_server }}:8080"
    gpgcheck: true
    gpgkey: "http://{{ hauler_server }}:8080/public.key"

- name: Install RKE2 rpm packages
  ansible.builtin.dnf:
    name: "{{ mount_rke2_selinux_rpm_path }}"
    state: present
  loop:
    - rke2-selinux
    - rke2-common
    - rke2-server
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version | int >= 8
