---
# RPM
- name: Import a key from a file
  ansible.builtin.rpm_key:
    state: present
    key: "{{ mount_rke2_path }}/public.key"
  when:
    - ansible_os_family == "RedHat"
- name: Install RKE2 selinux packages (dependency for RKE2 common)
  ansible.builtin.dnf:
    name: "{{ mount_rke2_selinux_rpm_path }}"
    state: present
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version | int >= 8

- name: Install RKE2 common packages
  ansible.builtin.dnf:
    name: "{{ mount_rke2_common_rpm_path }}"
    state: present
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version | int >= 8
