---
# As root
- name: Install with tarball method
  become: true
  block:
    - name: TARBALL | Make temp dir
      ansible.builtin.tempfile:
        state: directory
        suffix: rke2-install.
        path: "{{ tarball_tmp_dir | default(omit) }}"
      register: temp_dir

    - name: TARBALL | Get RKE2 Artifacts from URL
      ansible.builtin.get_url:
        url: "http://{{ hauler_server }}:8080/{{ item }}"
        dest: "{{ temp_dir['path'] }}/{{ item }}"
        validate_certs: false
      loop:
        - rke2-images.linux-amd64.tar.zst
        - rke2.linux-amd64.tar.gz
        - sha256sum-amd64.txt
        - install.sh

    - name: TARBALL | Install RKE2 server node
      ansible.builtin.shell:
        cmd: |
          set -o pipefail && INSTALL_RKE2_ARTIFACT_PATH={{ temp_dir['path'] }} INSTALL_RKE2_TYPE=server sh {{ temp_dir['path'] }}/install.sh
        chdir: "{{ temp_dir['path'] }}"
        executable: /bin/bash
      register: install_server_output
      failed_when: false
      changed_when: false

    - name: TARBALL | Display install output
      ansible.builtin.debug:
        var: install_server_output['stdout_lines']

    - name: TARBALL | Pause for 5 seconds before start service
      ansible.builtin.pause:
        seconds: 5
