---
# As root
- name: Get and write token
  become: true
  block:
    - name: Wait for node-token
      ansible.builtin.wait_for:
        path: "{{ rke2_data_dir }}/server/node-token"

    - name: Read node-token from master
      ansible.builtin.slurp:
        src: "{{ rke2_data_dir }}/server/node-token"
      register: node_token

    - name: Store Master node-token
      ansible.builtin.set_fact:
        rke2_config_token: "{{ node_token['content'] | b64decode | regex_replace('\n', '') }}"

    - name: Write token on mount path
      ansible.builtin.copy:
        content: "{{ rke2_config_token }}"
        dest: "{{ mount_rke2_path }}/token"
        follow: true
        mode: "0640"
