# Install and start iscsid 
- block:
  - name: Ensure iscsi-initiator-utils package is installed on Redhat based OS
    ansible.builtin.dnf:
      name:  iscsi-initiator-utils
      state: present

  - name: Start and enable iscsid
    ansible.builtin.systemd:
      name: iscsid
      state: started
      enabled: yes

  become: true
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version | int >= 8

- name: Ensure longhorn directory exist
  ansible.builtin.file:
    path: "{{ longhorn_datapath }}"
    state: directory
    recurse: true
    mode: '0750'
