---
# Remove service from zone
- name: Delete firewalld service {{ service['name'] }}
  ansible.builtin.firewalld:
    service: "{{ service['name'] }}"
    permanent: true
    immediate: true
    zone: "{{ service['zone'] | default( firewalld_default_zone ) }}"
    state: disabled

# Completely delete service
- name: Delete firewalld service definition {{ service['name'] }}
  ansible.builtin.file:
    path: "{{ firewalld_path }}/services/{{ service['name'] }}.xml"
    state: absent
  when:  service['erase'] == true
  notify: Restart firewalld

- name: Flush handlers now
  ansible.builtin.meta: flush_handlers