---
# tasks file for firewalld

- name: Manage firewalld zone files
  ansible.builtin.include_tasks: manage_firewalld_zone.yml
  loop: "{{ firewalld_zones  | default([]) }}"
  loop_control:
    loop_var: zone

- name: Manage inbound rules
  ansible.builtin.include_tasks: manage_inbound_rule.yml
  loop: "{{ firewalld_rules['inbound'] | default([]) }}"
  loop_control:
    loop_var: rule

- name: Delete a Service Completely
  ansible.builtin.include_tasks: delete_service.yml
  loop: "{{ firewalld_remove['inbound'] | default([]) }}"
  loop_control:
    loop_var: service
