---
- name: Manage firewalld file zone definition {{ zone['name'] }}
  ansible.builtin.template:
    src: zone.xml.j2
    dest: "{{ firewalld_path }}/zones/{{ zone['name'] }}.xml"
    owner: root
    group: root
    mode: "0644"
    force: true
  notify: Restart firewalld

- name: Flush handlers now
  ansible.builtin.meta: flush_handlers

- name: Manage firewalld zone definition {{ zone['name'] }}
  ansible.posix.firewalld:
    zone: "{{ zone['name'] }}"
    permanent: true
    immediate: true
    state: enabled