---
- name: Manage {{ zone['name'] }} firewalld file zone definition
  ansible.builtin.template:
    src: zone.xml.j2
    dest: "{{ firewalld_path }}/zones/{{ zone['name'] }}.xml"
    owner: root
    group: root
    mode: "0644"
    force: true
  notify: restart firewalld

- meta: flush_handlers

- name: Manage {{ zone['name'] }} firewalld zone definition
  ansible.builtin.firewalld:
    zone: "{{ zone['name'] }}"
    permanent: true
    immediate: true
    state: enabled