- name: Manage {{ zone['name'] }} firewalld file zone definition
  template:
    src: zone.xml.j2
    dest: "{{ firewalld_path }}/zones/{{ zone['name'] }}.xml"
    owner: root
    group: root
    mode: "0644"
    force: yes
  notify: restart firewalld

- meta: flush_handlers

- name: Manage {{ zone['name'] }} firewalld zone definition
  firewalld:
    zone: "{{ zone['name'] }}"
    permanent: yes
    immediate: yes
    state: enabled
