- name: Manage {{ rule['name'] }} firewalld service definition
  template:
    src: service.xml.j2
    dest: "{{ firewalld_path }}/services/{{ rule['name'] }}.xml"
    owner: root
    group: root
    mode: "0644"
    force: yes
  notify: restart firewalld

- meta: flush_handlers

- name: Manage {{ rule['name'] }} firewalld service
  firewalld:
    service: "{{ rule['name'] }}"
    permanent: yes
    immediate: yes
    zone: "{{ rule['zone'] | default( firewalld_default_zone ) }}"
    state: enabled
