---
- name: Manage firewalld service definition {{ rule['name'] }}
  ansible.builtin.template:
    src: service.xml.j2
    dest: "{{ firewalld_path }}/services/{{ rule['name'] }}.xml"
    owner: root
    group: root
    mode: "0644"
    force: true
  notify: Restart firewalld

- name: Flush handlers now
  ansible.builtin.meta: flush_handlers

- name: Manage firewalld service {{ rule['name'] }}
  ansible.posix.firewalld:
    service: "{{ rule['name'] }}"
    permanent: true
    immediate: true
    zone: "{{ rule['zone'] | default(firewalld_default_zone) }}"
    state: enabled
