---
- name: Compress files using zstd and create an archive
  ansible.builtin.command:
    "tar -I zstd -vcf {{ tar_zst_name }} -C {{ directory_package }} ."
  args:
    chdir: "{{ directory_package }}/.."