---
# Download/Install helm on build server
- name: Download Helm binary
  ansible.builtin.get_url:
    url: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: "{{ directory_package }}/helm/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    mode: 0750

- name: Install Helm binary
  ansible.builtin.shell: |
    tar -zxvf helm-{{ helm_version }}-linux-amd64.tar.gz > /dev/null 2>&1
    rsync -avP linux-amd64/helm /usr/local/bin/ > /dev/null 2>&1
    rm -rf linux-amd64 > /dev/null 2>&1
  args:
    chdir: "{{ directory_package }}/helm/"
  changed_when: false

# Add charts repository
- name: Add jetstack chart repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"
    force_update: true

- name: Add jetstack chart repo
  kubernetes.core.helm_repository:
    name: rancher-latest
    repo_url: "https://releases.rancher.com/server-charts/latest"
    force_update: true

- name: Add longhorn chart repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: "https://charts.longhorn.io"
    force_update: true

- name: Add neuvector chart repo
  kubernetes.core.helm_repository:
    name: neuvector
    repo_url: "https://neuvector.github.io/neuvector-helm/"
    force_update: true

# Pull charts
- name: Download chart using chart url
  kubernetes.core.helm_pull:
    chart_ref: jetstack/cert-manager
    chart_version: "v{{ CERT_VERSION }}"
    destination: "{{ directory_package }}/helm/"

- name: Download chart using chart url
  kubernetes.core.helm_pull:
    chart_ref: rancher-latest/rancher
    chart_version: "v{{ RANCHER_VERSION }}"
    destination: "{{ directory_package }}/helm/"

- name: Download chart using chart url
  kubernetes.core.helm_pull:
    chart_ref: longhorn/longhorn
    chart_version: "{{ LONGHORN_VERSION }}"
    destination: "{{ directory_package }}/helm/"

- name: Download chart using chart url
  kubernetes.core.helm_pull:
    chart_ref: neuvector/core
    chart_version: "{{ NEU_VERSION }}"
    destination: "{{ directory_package }}/helm/"
