---
# tasks file for build_airgap_package
- name: Gather facts
  ansible.builtin.setup:
    gather_subset:
      - "distribution"
      - "distribution_major_version"
      - "!min"
  when: >
    ansible_os_family is not defined

- name: Prerequisites
  ansible.builtin.import_tasks: prerequis.yml

- name: Import utils binaries
  ansible.builtin.import_tasks: utils.yml

- name: Import RKE2
  ansible.builtin.import_tasks: rke2.yml

- name: Import helm charts
  ansible.builtin.import_tasks: helm.yml

- name: Import images
  ansible.builtin.import_tasks: images.yml

- name: Compress the all thing
  ansible.builtin.import_tasks: compress.yml