---
- name: Download rke2-images.linux-amd64.tar.zst
  ansible.builtin.get_url:
    url: "https://github.com/rancher/rke2/releases/download/{{ rke2_common_repo_version }}/rke2-images.linux-amd64.tar.zst"
    dest: "{{ directory_package }}/rke2_{{ rke2_version }}/rke2-images.linux-amd64.tar.zst"
    mode: "0750"

- name: Download rke2.linux-amd64.tar.gz
  ansible.builtin.get_url:
    url: "https://github.com/rancher/rke2/releases/download/{{ rke2_common_repo_version }}/rke2.linux-amd64.tar.gz"
    dest: "{{ directory_package }}/rke2_{{ rke2_version }}/rke2.linux-amd64.tar.gz"
    mode: "0750"

- name: Download sha256sum-amd64.txt
  ansible.builtin.get_url:
    url: "https://github.com/rancher/rke2/releases/download/{{ rke2_common_repo_version }}/sha256sum-amd64.txt"
    dest: "{{ directory_package }}/rke2_{{ rke2_version }}/sha256sum-amd64.txt"
    mode: "0750"

- name: Download repo GPG key
  ansible.builtin.get_url:
    url: "https://rpm.rancher.io/public.key"
    dest: "{{ directory_package }}/rke2_{{ rke2_version }}/public.key"
    mode: "0750"

- name: Download get.rke2.io
  ansible.builtin.get_url:
    url: "https://get.rke2.io"
    dest: "{{ directory_package }}/rke2_{{ rke2_version }}/install.sh"
    mode: "0750"

# if localhost is RHEL-like take packages for the current major version
- name: Download if localhost RHEL-like and take same version than localhost
  when:
    - ansible_os_family == "RedHat"
  block:
    - name: Download rke2-common RPM
      ansible.builtin.get_url:
        url: "https://github.com/rancher/rke2-packaging/releases/download/{{ rke2_common_repo_version }}.stable.0/{{ rke2_common_rpm_version }}.el{{ ansible_distribution_major_version }}.x86_64.rpm"
        dest: "{{ directory_package }}/rke2_{{ rke2_version }}/{{ rke2_common_rpm_version }}.el{{ ansible_distribution_major_version }}.x86_64.rpm"
        mode: "0750"

    - name: Download rke2-selinux RPM
      ansible.builtin.get_url:
        url: "https://github.com/rancher/rke2-selinux/releases/download/{{ rke2_selinux_repo_version }}/{{ rke2_selinux_rpm_version }}.el{{ ansible_distribution_major_version }}.noarch.rpm"
        dest: "{{ directory_package }}/rke2_{{ rke2_version }}/{{ rke2_selinux_rpm_version }}.el{{ ansible_distribution_major_version }}.noarch.rpm"
        mode: "0750"

    - name: Download rke2-images.linux-amd64.tar.zst
      ansible.builtin.get_url:
        url: "https://github.com/rancher/rke2-packaging/releases/download/v{{ rke2_version }}%2Brke2r1.stable.0/{{ item }}"
        dest: "{{ directory_package }}/rke2_{{ rke2_version }}/{{ item }}"
        mode: "0750"
      loop:
        - rke2-common-{{ rke2_version }}.rke2r1-0.el{{ ansible_distribution_major_version }}.x86_64.rpm
        - rke2-agent-{{ rke2_version }}.rke2r1-0.el{{ ansible_distribution_major_version }}.x86_64.rpm
        - rke2-server-{{ rke2_version }}.rke2r1-0.el{{ ansible_distribution_major_version }}.x86_64.rpm

# if localhost is not a RHEL-like take el8
- name: Download if localhost not a RHEL-like and take by default el8
  when:
    - ansible_os_family != "RedHat"
  block:
    - name: Download rke2-common RPM
      ansible.builtin.get_url:
        url: "https://github.com/rancher/rke2-packaging/releases/download/{{ rke2_common_repo_version }}.stable.0/{{ rke2_common_rpm_version }}.el8.x86_64.rpm"
        dest: "{{ directory_package }}/rke2_{{ rke2_version }}/{{ rke2_common_rpm_version }}.el8.x86_64.rpm"
        mode: "0750"

    - name: Download rke2-selinux RPM
      ansible.builtin.get_url:
        url: "https://github.com/rancher/rke2-selinux/releases/download/{{ rke2_selinux_repo_version }}/{{ rke2_selinux_rpm_version }}.el8.noarch.rpm"
        dest: "{{ directory_package }}/rke2_{{ rke2_version }}/{{ rke2_selinux_rpm_version }}.el8.noarch.rpm"
        mode: "0750"

    - name: Download rke2-images.linux-amd64.tar.zst
      ansible.builtin.get_url:
        url: "https://github.com/rancher/rke2-packaging/releases/download/v{{ rke2_version }}%2Brke2r1.stable.0/{{ item }}"
        dest: "{{ directory_package }}/rke2_{{ rke2_version }}/{{ item }}"
        mode: "0750"
      loop:
        - rke2-common-{{ rke2_version }}.rke2r1-0.el8.x86_64.rpm
        - rke2-agent-{{ rke2_version }}.rke2r1-0.el8.x86_64.rpm
        - rke2-server-{{ rke2_version }}.rke2r1-0.el8.x86_64.rpm
