- name: Get Latest version of arkade
  ansible.builtin.get_url:
    url: "{{ lookup('url', 'https://api.github.com/repos/alexellis/arkade/releases/latest', split_lines=false) | regex_search('browser_download_url.*(https://github.com/alexellis/arkade/releases/download(.*?)/arkade)', '\\1') | first }}"
    dest: '{{ directory_package }}/utils/arkade'
    mode: '0740'

- name: Arkade get packages
  ansible.builtin.shell:
    "{{ directory_package }}/utils/arkade get --progress=false --path {{ directory_package }}/utils/ {{ item }} > /dev/null"
  loop: 
    - yq
    - jq
    - helm
    - just
    - nerdctl
    - k9s
    - kubectl