debug          = false
debug_full     = false
address        = "unix:///run/k3s/containerd/containerd.sock"
namespace      = "k8s.io"
hosts_dir      = ["/etc/containerd/certs.d", "/etc/docker/certs.d"]