output "master_ips" {
  description = "The IP addresses of the master VMs."
  value       = flatten([for m in libvirt_domain.masters : m.network_interface[0].addresses])
}

output "worker_ips" {
  description = "The IP addresses of the worker VMs."
  value       = flatten([for w in libvirt_domain.workers : w.network_interface[0].addresses])
}

###
### Generate the hosts.ini file
###

# ipv6 generated by fedora cloud image...so it false the inventory
resource "null_resource" "sleep_before_inventory" {
  provisioner "local-exec" {
    command = "sleep 60"  # Adjust the sleep duration as needed
  }

  depends_on = [libvirt_domain.masters, libvirt_domain.workers]
}
resource "local_file" "ansible_inventory" {
  content = templatefile("../inventory/hosts.tpl",
    {
      controller_ips = flatten([for m in libvirt_domain.masters : [for addr in m.network_interface[0].addresses : addr if can(regex("^\\d+\\.\\d+\\.\\d+\\.\\d+$", addr))]]),
      worker_ips     = flatten([for w in libvirt_domain.workers : [for addr in w.network_interface[0].addresses : addr if can(regex("^\\d+\\.\\d+\\.\\d+\\.\\d+$", addr))]])
    }
  )
  filename = "../inventory/hosts.ini"
  depends_on = [null_resource.sleep_before_inventory]
}