- name: Remove admin user (if different from root)
  ansible.builtin.user:
    name: "{{ admin_user }}"
    state: absent
    remove: yes
  failed_when: false
  when: 
    - admin_user is defined 
    - admin_user != "root" 