---
# tasks file for uninstall_rke2
- name: Gather facts
  ansible.builtin.setup:
    gather_subset:
      - "distribution"
      - "distribution_major_version"
      - "default_ipv4"
      - "!all,!min"
  when: >
    ansible_os_family is not defined
  tags: [always]

- name: Populate service facts
  ansible.builtin.service_facts: {}
  tags: [always]

- name: RKE2 Uninstall
  ansible.builtin.import_tasks: uninstall.yml

- name: Utils Uninstall
  ansible.builtin.import_tasks: utils.yml

- name: Admin Uninstall
  ansible.builtin.import_tasks: admin.yml

- name: NFS Uninstall
  ansible.builtin.import_tasks: nfs.yml

- name: RKE2 firewalld remove
  vars:
    firewalld_remove: "{{ firewalld_rules_to_remove }}"
  ansible.builtin.import_role:
    name: set_firewalld
    tasks_from: main
  when:
    - ansible_facts['services']['firewalld.service'] is defined
    - ansible_facts['services']['firewalld.service']['state'] == "running"