- block:

  - name: Unmount NFS share
    ansible.posix.mount:
      path: "{{ nfs_mount_path }}"
      state: unmounted

  - name: Remove NFS entry from /etc/fstab
    ansible.builtin.lineinfile:
      path: /etc/fstab
      regexp: ".*{{ nfs_mount_path }} nfs.*"
      state: absent

  - name: Remove mount directory
    ansible.builtin.file:
      path: "{{ nfs_mount_path }}"
      state: absent

  - name: Share out directory via NFS
    ansible.builtin.lineinfile:
      path: /etc/exports
      line: "{{ export_nfs_path }} *(ro)"
      state: absent

  - name: Remove NFS packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: absent
    with_items:
      - nfs-utils
    when:
      - ansible_os_family == "RedHat"
      - ansible_distribution_major_version | int >= 8

  become: true

# Remove NFS firewalld 
- block: 

  - name: firewalld NFS port enabled 
    ansible.posix.firewalld:
      service: nfs
      permanent: true
      state: disabled 

  - name: Always reload firewalld
    ansible.builtin.service:
      name: firewalld
      state: reloaded

  become: true
  when:
    - ansible_facts['services']['firewalld.service'] is defined
    - ansible_facts['services']['firewalld.service']['state'] == "running"