- block:

  - name: Unmount NFS share
    ansible.posix.mount:
      path: "{{ nfs_mount_path }}"
      state: unmounted

  - name: Remove NFS entry from /etc/fstab
    ansible.builtin.lineinfile:
      path: /etc/fstab
      regexp: ".*{{ nfs_mount_path }} nfs.*"
      state: absent

  - name: Remove mount directory
    ansible.builtin.file:
      path: "{{ nfs_mount_path }}"
      state: absent

  - name: Share out directory via NFS
    ansible.builtin.lineinfile:
      path: /etc/exports
      line: "{{ export_nfs_path }} *(ro)"
      state: absent

  - name: Remove NFS packages
    dnf:
      name: "{{ item }}"
      state: absent
    with_items:
      - nfs-utils
    when:
      - ansible_os_family == "RedHat"
      - ansible_distribution_major_version | int >= 8

  become: true