

- name: Pre-load registry image
  ansible.builtin.copy:
    src: "{{ airgap_registry_tar }}"
    dest: "{{ rke2_images_path }}"
    remote_src: true

- name: "Kubernetes execution from Ansible controler"
  #delegate_to: localhost
  run_once: true
  become: false
  block:

  - name: Deploy registry manifest
    kubernetes.core.k8s:
      state: present
      template: "{{ item }}"
      kubeconfig: "~/.kube/{{ inventory_hostname }}.yaml"
    loop:
      - registry.yaml.j2