---
# Load Neuvector
- name: Find Neuvector images on the target server
  ansible.builtin.find:
    paths: "{{ mount_images_path }}/neuvector/"
    patterns: "*.tar"
  register: found_images

- name: Copy Neuvector images with skopeo
  ansible.builtin.command: "skopeo copy docker-archive:{{ item.path }} docker://localhost:5000/neuvector/{{ item.path | basename | regex_replace('.tar', '') | regex_replace('_', ':') }} --dest-tls-verify=false"
  changed_when: false
  with_items: "{{ found_images['files'] }}"
