---
- name: Flush handlers now
  ansible.builtin.meta: flush_handlers

- name: Wait for k8s apiserver
  ansible.builtin.wait_for:
    host: localhost
    port: "5000"
    state: present
    timeout: 600
