---
# tasks file for install_local_registry
- name: Push registry tar in RKE2 images
  ansible.builtin.import_tasks: push.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Copy manifest
  ansible.builtin.import_tasks: manifest.yml
  when: caller_role_name == "controller"

- name: Kubernetes tasks
  ansible.builtin.import_tasks: deploy.yml
  when: caller_role_name == "controller"

- name: Load images in local registry
  ansible.builtin.import_tasks: load.yml
  when: caller_role_name == "controller"

- name: List images imported in registry
  ansible.builtin.import_tasks: post.yml
  when: caller_role_name == "controller"
