---
- name: Ensure RKE2 manifests directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ rke2_data_path }}/server/manifests"
    owner: root
    group: root
    mode: 0700

- name: Copy registry manifest to first server
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ rke2_data_path }}/server/manifests/{{ item | basename | regex_replace('.j2$', '') }}"
    owner: root
    group: root
    mode: 0664
  with_fileglob:
    - "registry.yaml.j2"
