---

# Result
- name: List docker registry
  ansible.builtin.shell:
    cmd: |
      set -o pipefail &&
      source $HOME/.bashrc &&
      for i in $(curl -sk localhost:5000/v2/_catalog | jq -r '.repositories[]'); do
        for tag in $(curl -sk localhost:5000/v2/${i}/tags/list | jq -r '.tags[]'); do
          echo ${i}:${tag};
        done;
      done
    executable: /bin/bash
  register: docker
  changed_when: false
  become: true
  become_user: "{{ admin_user }}"

- name: Display Output
  ansible.builtin.debug:
    var: docker['stdout_lines']
