- name: Pre-load registry image
  ansible.builtin.copy:
    src: "{{ mount_registry_tar }}"
    dest: "{{ rke2_images_path }}"
    remote_src: true
  notify: Restart rke2-server
  when:  caller_role_name == "controller"

- name: Pre-load registry image
  ansible.builtin.copy:
    src: "{{ mount_registry_tar }}"
    dest: "{{ rke2_images_path }}"
    remote_src: true
  notify: Restart rke2-agent
  when: caller_role_name == "worker"  

- name: Flush handlers
  ansible.builtin.meta: flush_handlers