---
# As root
- name: Install Nerdctl
  become: true
  block:
    - name: Create the NERDCTL directory
      ansible.builtin.file:
        path: /etc/nerdctl
        state: directory
        mode: '0754'

    - name: Check if file does exist
      ansible.builtin.stat:
        path: /usr/local/bin/nerdctl
      register: file_data

    - name: Push nerdctl when not already here
      when: not file_data.stat.exists
      block:
        - name: Create tmp dir
          ansible.builtin.file:
            path: /tmp/nerdctl
            state: directory
            mode: '0750'

        - name: Download Nerdctl bin into /usr/local/bin
          ansible.builtin.unarchive:
            src: "http://{{ hauler_server }}:8080/nerdctl.tar.gz"
            dest: "/tmp/nerdctl"
            mode: '0750'
            remote_src: true
            validate_certs: false

        - name: Copy nerdctl binary file
          ansible.builtin.copy:
            src: "/tmp/nerdctl/nerdctl"
            dest: "/usr/local/bin/nerdctl"
            mode: '0750'

        - name: Cleanup tmp dir
          ansible.builtin.file:
            path: /tmp/nerdctl
            state: absent
            recurse: true

    - name: Copy NERDCTL configuration file
      ansible.builtin.template:
        src: nerdctl.toml
        dest: /etc/nerdctl
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: '0644'

    - name: Copy SUDO configuration
      ansible.builtin.template:
        src: secure-path
        dest: /etc/sudoers.d
        owner: "root"
        group: "root"
        mode: '0440'
