---
# packages on all nodes needed
- name: Install packages common
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - tar
    - gzip
  become: true
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version | int >= 8

- name: Install packages common
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - tar
    - gzip
  become: true
  when:
    - ansible_os_family == "Debian"
