---
# tasks file for install_common
- name: Gather facts
  setup:
    gather_subset:
      - "distribution"
      - "distribution_major_version"
      - "!min"
  when: >
    ansible_os_family is not defined

- name: Tasks common to Linux servers
  import_tasks: linux.yml

- name: Tasks for RHEL-like OS
  import_tasks: rhel.yml
  when:
    - ansible_os_family == "RedHat"