---
# tasks file for install_common
- name: Gather facts
  ansible.builtin.setup:
    gather_subset:
      - "distribution"
      - "distribution_major_version"
      - "!min"
  when: >
    ansible_os_family is not defined

- name: Tasks common to Linux servers
  ansible.builtin.import_tasks: linux.yml

- name: Tasks for RHEL-like OS
  ansible.builtin.import_tasks: rhel.yml
  when:
    - ansible_os_family == "RedHat"

- name: Install nerdctl on all nodes
  ansible.builtin.import_tasks: nerdctl.yml
