---
# tasks file for install_common
- name: Gather facts
  ansible.builtin.setup:
    gather_subset:
      - "distribution"
      - "distribution_major_version"
      - "!min"
  when: >
    ansible_os_family is not defined

- name: Tasks common to Linux servers for RKE2 installation
  ansible.builtin.import_tasks: install.yml

- name: Get Token if one exist
  ansible.builtin.import_tasks: token.yml

- name: RKE2 Install specific for RHEL-like OS
  ansible.builtin.import_tasks: rhel.yml
  when: ansible_os_family == "RedHat"
  tags: rhel
