---
# tasks file for install_common
- name: Gather facts
  ansible.builtin.setup:
    gather_subset:
      - "distribution"
      - "distribution_major_version"
      - "!min"
  when: >
    ansible_os_family is not defined
  tags: [always]

- name: Populate service facts
  ansible.builtin.service_facts: {}
  when: >
    ansible_facts['services'] is not defined
  tags: [always]

- name: Specific config for NetworkManager
  ansible.builtin.import_tasks: networkmanager.yml
  when:
    - ansible_facts['services']['NetworkManager.service'] is defined
  tags: networkmanager

- name: Tasks common to Linux servers for RKE2 installation
  ansible.builtin.import_tasks: common.yml

- name: Get Token if one exist
  ansible.builtin.import_tasks: token.yml
  when: caller_role_name != "first_controller"

- name: RKE2 Install specific for RHEL-like OS
  ansible.builtin.import_tasks: rhel.yml
  when: ansible_os_family == "RedHat"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
