# For RHEL >= 8 as root
- block:
    - name: Display message
      debug:
        msg: "Specific actions regarding servers in RHEL 8/9"

    # Desactivate Cloud services
    - name: Disable service nm-cloud-setup
      ansible.builtin.systemd:
        name: nm-cloud-setup.service
        enabled: no
        state: stopped
      when: ansible_facts.services["nm-cloud-setup.service"] is defined

    - name: Disable nm-cloud-setup.timer unit
      ansible.builtin.systemd:
        name: nm-cloud-setup.timer
        state: stopped
        enabled: no
      when: ansible_facts.services["nm-cloud-setup.service"] is defined

    # Networker config
    - name: Configure NetworkManager for RKE2 and Canal
      ansible.builtin.copy:
        content: |
          [keyfile]
          unmanaged-devices=interface-name:cali*;interface-name:flannel*
        dest: /etc/NetworkManager/conf.d/rke2-canal.conf
      when: ansible_facts.services["NetworkManager.service"] is defined

    - name: Set rke2-canal.conf file permissions
      ansible.builtin.file:
        path: /etc/NetworkManager/conf.d/rke2-canal.conf
        mode: '0600'
        owner: root
        group: root
      when: ansible_facts.services["NetworkManager.service"] is defined

    - name: Reload NetworkManager
      ansible.builtin.systemd:
        name: NetworkManager
        state: reloaded
      when: (ansible_facts.services["NetworkManager.service"] is defined) and
            (ansible_facts.services["NetworkManager.service"].status == "running")

  become: true
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version | int >= 8

# For RHEL 7 as root
- block:
    - name: Display message
      debug:
        msg: "Specific actions regarding servers in RHEL 7"

  become: true
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version | int == 7