---
# For RHEL >= 8 as root
- name: Specific actions to be done on RHEL 8
  become: true
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version | int >= 8
  block:
    # Desactivate Cloud services
    - name: Disable service nm-cloud-setup
      ansible.builtin.systemd:
        name: nm-cloud-setup.service
        enabled: false
        state: stopped
      when: ansible_facts['services']['nm-cloud-setup.service'] is defined

    - name: Disable nm-cloud-setup.timer unit
      ansible.builtin.systemd:
        name: nm-cloud-setup.timer
        state: stopped
        enabled: false
      when: ansible_facts['services']['nm-cloud-setup.service'] is defined

# For RHEL 7 as root
- name: Specific actions to be done on RHEL 7
  become: true
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version | int == 7
  block:
    - name: Display message
      ansible.builtin.debug:
        msg: "Specific actions regarding servers in RHEL 7"
