---
## Get Token if one exist
- name: Get token from URL
  ansible.builtin.uri:
    url: "http://{{ hauler_server }}:8080/token"
    method: GET
    validate_certs: false
    return_content: true
  register: token_response
  failed_when: false

- name: Debug URL
  ansible.builtin.debug:
    var: token_response

- name: Set variable with token
  ansible.builtin.set_fact:
    rke2_config_token: "{{ token_response['content'] }}"
  when: token_response.status == 200
