---
name: Update Readme and Changelog
description: Update Readme and Changelog

runs:
  using: composite
  steps:
    # Update Readme 
    - shell: bash
      run: |
        rke2_version=$( yq -r .global_rke2_version  playbooks/vars/main.yml)
        cert_version=$( yq -r .global_CERT_VERSION  playbooks/vars/main.yml)
        rancher_version=$( yq -r .global_RANCHER_VERSION  playbooks/vars/main.yml)
        longhorn_version=$( yq -r .global_LONGHORN_VERSION  playbooks/vars/main.yml)
        neuvector_version=$( yq -r .global_NEU_VERSION playbooks/vars/main.yml)

        echo "  - [RKE2 ${rke2_version}](https://docs.rke2.io) - Security focused Kubernetes" >>  version.txt
        echo "  - [Rancher ${cert_version}](https://www.suse.com/products/suse-rancher/) - Multi-Cluster Kubernetes Management" >>  version.txt
        echo "  - [Longhorn ${longhorn_version}](https://longhorn.io) - Unified storage layer" >>  version.txt
        echo "  - [Neuvector ${neuvector_version}](https://neuvector.com/) - Kubernetes Security Platform" >>  version.txt

        sed -i -n -e "1,/<\!-- Autogenerated -->/ p" -e"/<\!-- END -->/,$ p" -e "/<\!-- Autogenerated -->/ r version.txt" README.md

        rm -f version.txt

    # Update Changelog
    #- shell: bash
    #  run: |

    # Git push 
    - shell: bash
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add README.md
        [[ -z $(git status -uno --porcelain) ]] && echo "No need to commit..." || git commit -m "⚡ Update README"
        git push origin