---
- name: Hauler Server
  hosts: "{{ hauler_ip | default('RKE2_CONTROLLERS[0]') }}"
  gather_facts: false
  vars_files: ../vars/main.yml
  tags: [ registry, fileserver ]
  roles:
    - {role: mozebaltyk.rkub.deploy_hauler, tags: hauler}
