---
- name: Install Longhorn
  hosts: RKE2_CONTROLLERS:RKE2_WORKERS
  gather_facts: true
  become: true
  vars_files: ../vars/main.yml
  tags: [ controller, worker ]
  roles:
    - {role: mozebaltyk.rkub.deploy_longhorn, tags: longhorn}
