---
- name: Uninstall RKE2
  hosts: RKE2_CONTROLLERS:RKE2_WORKERS
  gather_facts: false
  become: true
  vars_files: ../vars/main.yml
  tags: controler, worker
  roles:
    - {role: mozebaltyk.rkub.uninstall_rkub, tags: uninstall}
