---
name: Build
on:
  workflow_dispatch:

  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Which branch?
        shell: bash
        run: |
          echo "${{ github.head_ref || github.ref_name }}"

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      # step to install prerequis
      - name: Install prerequis
        shell: bash
        run: |
          make prerequis

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
