name: Release
on:
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest
    name: Update Rkub Readme

    if: github.repository == 'mozebaltyk/rkub'
    permissions:
      actions: write
      checks: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Update Readme
        uses: ./.github/actions/update-readme