---
name: Stage deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Get tag name
        uses: olegtarasov/get-tag@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Terraform Init
        id: init
        run: |
          cd test/
          terraform init

      - run: 'echo "$SSH_KEY" > .key'
        shell: bash
        env:
          SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}

      - run: chmod 400 .key

      - name: Terraform private key
        run: cp .key test/.key

      - name: Terraform Validate
        id: validate
        run: |
          cd test/
          terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: |
          cd test/
          terraform plan -var "GITHUB_RUN_ID=$GITHUB_RUN_ID" -var "do_token=${DO_PAT}" -no-color
        continue-on-error: true
        env:
          DO_PAT: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: |
          cd test/
          terraform apply -var "GITHUB_RUN_ID=$GITHUB_RUN_ID" -var "do_token=${DO_PAT}" -auto-approve
        env:
          DO_PAT: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Set up Python
        id: setup_python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install ansible pytest-testinfra

      - name: Ansible Version check
        run: ansible --version

      - name: Create inventory hosts.ini
        run: |
          touch hosts.ini
          echo "[RKE2_CONTROLLERS]" > hosts.ini
          doctl compute droplet list --no-header --tag-name rke2_ansible_test_on_rockylinux-8-x64_${GITHUB_RUN_ID}_controllers --format "Public IPv4" --output text >> hosts.ini
          echo "[RKE2_WORKERS]" >> hosts.ini
          doctl compute droplet list --no-header --tag-name rke2_ansible_test_on_rockylinux-8-x64_${GITHUB_RUN_ID}_workers --format "Public IPv4" --output text >> hosts.ini
          echo "[all:vars]" >> hosts.ini
          echo "kubernetes_api_server_host=$(echo " " | head -1)" >> hosts.ini
          echo "" >> ansible.cfg
          echo "" >> ansible.cfg
          echo "remote_user=root" >> ansible.cfg
          echo "private_key_file=.key" >> ansible.cfg
        env:
          DO_PAT: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Check hosts.ini and ansible.cfg
        run: |
          cat hosts.ini
          cat ansible.cfg

      - name: Test if reachable
        run: |
          ANSIBLE_HOST_KEY_CHECKING=False ansible all -m ping -i hosts.ini -u root -vv --private-key .key

      #- name: Run playbook
      #  run: |
      #    ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i hosts.ini -u root -vv --private-key .key site.yml

      #- name: Run playbook again for idempotency
      #  run: |
      #    ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i hosts.ini -u root -vv --private-key .key site.yml

      #- name: Run Ansible Tests
      #  run: |
      #    ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i hosts.ini -u root --verbose --skip-tags "troubleshooting" --private-key .key testing.yml

      #- name: Run Python Tests
      #  run: |
      #    export DEFAULT_PRIVATE_KEY_FILE=.key
      #    pytest --hosts=rke2_servers --ansible-inventory=hosts.ini --force-ansible --connection=ansible --sudo test/basic_server_tests.py
      #    pytest --hosts=rke2_agents --ansible-inventory=hosts.ini --force-ansible --connection=ansible --sudo test/basic_agent_tests.py

      - name: Delete Stack
        if: ${{ always() }}
        run: |
          cd test/
          terraform destroy -var "GITHUB_RUN_ID=$GITHUB_RUN_ID" -var "do_token=${DO_PAT}" -auto-approve
        env:
          DO_PAT: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
