name: Release on Ansible Galaxy
on:
  workflow_dispatch:
  #push:
  #  branches: ["develop"]
  pull_request:
    branches: ["main"]

jobs:
  version:
    runs-on: ubuntu-latest
    name: Update Versions

    if: github.repository == 'mozebaltyk/rkub'
    permissions:
      actions: write
      checks: write
      contents: write

    steps:
      - name: Update Readme and changelog
        uses: ./.github/actions/update-readme
